[shell]
program = "/bin/zsh"
args = ["-l", "-ic", "tmux a -t base || tmux new -t base"]

[font]
size = 12

[font.normal]
family = "UDEV Gothic 35NF"
style = "Regular"

# ! copy from one_dark
# Default colors
[colors.primary]
background = '#1e2127'
foreground = '#abb2bf'

# Normal colors
[colors.normal]
black   = '#1e2127'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'

# Bright colors
[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'
# ! end

[selection]
save_to_clipboard = true

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key = "Q"
mods = "Control"
chars = "\u0011"

[[keyboard.bindings]]
key = "Semicolon"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "N"
mods = "Control"
action = "CreateNewWindow"

[[keyboard.bindings]]
key = "¥"
mods = "Control"
chars = "\\"

[window] # want to use forword-word but...
option_as_alt = "Both" # commentout bacause \ cannot type
